import React from "react";
import Head from "next/head";

import styles from '../../styles/Question.module.scss'

//[id].tsx id是动态参数，会根据传入的参数id进行url的访问
//临时引用
import QuestionInput from "@/components/QuestionComponents/QuestionInput";
import QuestionRadio from "@/components/QuestionComponents/QuestionRadio";

type PropsType={
    id:string
}

export default function Question(props:PropsType){

    return <>
    <Head>
        <title>Question</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <main>
        {/* 提交之后数据会到这个answer里面去 */}
        <form method="post" action='/api/answer'>
            {/* //隐藏了之后看不见id，但是依然存在，在提交时可以提交 */}
            <input name="questionId" defaultValue={props.id} type="hidden"/> 
            <div className={styles.componentWrapper}>
                <QuestionInput fe_id="c1" props={{title:'你的姓名', placeholder: '请输入姓名'}} />
            </div>
            <div className={styles.componentWrapper}>
                <QuestionRadio fe_id="c2" props={{
                title:'你的性别',
                options:[{
                    value:'male',text:'男'
                },
                {
                    value:'female',text:'女'
                }],
                value:'',
                isVertical:true
            }}/>
            </div>
            
            
            <div className={styles.submitBtnContainer}>
                <button type="submit">提交</button>
            </div>
        </form>
    </main>
    </>
}

//action='api/answer'